name: Plato
version: 1.0.2
github: "ksrky/Plato"
license: BSD3
author: "ksrk"
maintainer: "kswgrky@gmail.com"
copyright: "2022 ksrk"

language: GHC2021

extra-source-files:
  - compiler/metainfo.json

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ksrky/Plato#readme>

dependencies:
  - base >= 4.7 && < 5
  - array
  - bytestring
  - containers
  - directory
  - filepath
  - hslogger
  - mtl
  - prettyprinter
  - recursion-schemes
  - safe-exceptions
  - transformers
  - text
  - vector

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-name-shadowing

default-extensions:
  - OverloadedStrings
  - ImportQualifiedPost

library:
  source-dirs: compiler
  build-tools:
    - alex
    - happy

executables:
  plato:
    main: Main.hs
    source-dirs: driver/plato
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Plato
      - aeson
      - haskeline
      - optparse-applicative
      - template-haskell

tests:
  Plato-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Plato
      - hspec
      - hspec-discover
    build-tools:
      - hspec-discover:hspec-discover
