name: Plato
version: 0.1.0.0
github: "ksrky/Plato"
license: BSD3
author: "ksrk"
maintainer: "example@example.com"
copyright: "2022 ksrk"

extra-source-files:
  - README.md
  - ChangeLog.md

build-tools:
  - alex
  - happy

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ksrky/Plato#readme>

dependencies:
  - base >= 4.7 && < 5
  - array
  - containers
  - haskeline
  - hspec
  - mtl
  - safe-exceptions
  - text

library:
  source-dirs: src

executables:
  Plato-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Plato

tests:
  Plato-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Plato
