site_name: Plato
repo_url: https://github.com/ksrky/Plato/
site_author: ksrk
copyright: 2022 ksrk
site_dir: ../site/en

nav:
  - Home: index.md
  - Getting Started:
      - Preface: getting-started/preface.md
      - Installation: getting-started/installation.md
  - Langauge Reference:
      - Language Reference: language-reference/index.md
      - Core Lanaguage: language-reference/core-language.md
  - Implementation Notes: implementation-notes/index.md
theme:
  name: material
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Japanese
      link: /ja/
      lang: ja
markdown_extensions:
  - pymdownx.arithmatex
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"
