site_name: Plato
site_url: https://ksrky.github.io/Plato/ja/
site_author: ksrk
copyright: 2022 ksrk
site_dir: ../../site/ja
repo_url: https://github.com/ksrky/Plato/
edit_uri: blob/master/docs/ja/docs

nav:
  - Home: index.md
  - Plato入門:
      - 入門: getting-started/index.md
      - インストール: getting-started/installation.md
  - 言語仕様: language-reference/index.md
  - 実装上の議論: implementation-notes/index.md
theme:
  name: material
  language: ja
extra:
  alternate:
    - name: English
      link: /Plato/en/
      lang: en
    - name: Japanese
      link: /Plato/ja/
      lang: ja
markdown_extensions:
  - pymdownx.arithmatex
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
