site_name: Plato
site_url: https://ksrky.github.io/Plato/
site_author: ksrk
copyright: 2022 ksrk
site_dir: ../../site/ja
repo_url: https://github.com/ksrky/Plato/
edit_uri: blob/master/docs/ja/docs

nav:
  - Home: index.md
  - Plato入門:
      - 入門: getting-started/index.md
      - インストール: getting-started/installation.md
      - チュートリアル: getting-started/tutorial.md
  - 言語仕様:
      - コア言語: language-reference/core-language.md
      - 宣言: language-reference/declarations.md
      - 式: language-reference/expressions.md
      - 字句構造: language-reference/lexical-structure.md
      - プログラム構造: language-reference/program-structure.md
      - 再帰関数: language-reference/recursive-function.md
      - 型: language-reference/types.md
  - 実装上の議論:
      - コンパイラの構成: implementation-notes/compiler-structure.md
theme:
  name: material
  language: ja
markdown_extensions:
  - pymdownx.arithmatex
  - attr_list
  - md_in_html
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
