name: Plato Github Pages

on:
  push:
    branches: ["master"]

jobs:
  # Build & deploy job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Setup python env
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: docs
      - name: Build MkDocs
        run: mkdocs build --config-file en/mkdocs.yml
        working-directory: docs/en
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --config-file en/mkdocs.yml
